README.md
arb-bot.js
example.env
src/index.js
src/query.js

- Updated default subgraph url. 
- Added option to lock the bot onto a particular order by mention the `order-hash`. 
- Removed Negative estimates as it will be added in further updates.

Bot Updates

---

config.json
src/index.js
src/modes/suniv2.js
src/utils.js
test/suniv2.test.js

fix `suniv2` mode bug

---

src/modes/crouter.js
src/modes/curve.js
src/modes/router.js
src/modes/srouter.js
src/modes/zeroex.js

log order ids

---

.github/workflows/standard-test.yaml
arb-bot.js
hardhat.config.js
src/index.js
src/modes/srouter.js
src/utils.js
test/modeTests/srouter.test.js

reduce spans size

---

src/index.js
src/query.js

sg status check

---

arb-bot.js
src/index.js
src/modes/srouter.js
src/query.js
src/utils.js
test/orders.test.js
test/utils.js

there is risk and bug when not using sg JSON order details, which can result in submitting arb with bad orders details, resulting in wrong hash recalculation.
resolves #93 
use sg JSON entity

use sg json order details

---

README.md
arb-bot.js
example.env
hardhat.config.js
package-lock.json
package.json
src/abis.js
src/index.js
src/modes/srouter.js
src/utils.js
test/e2e/e2e.test.js
test/modeTests/srouter.test.js
test/options.test.js
test/orders.test.js
test/processPair.test.js

resolves #95 
get vault balance and use it as start value for binary search for `maximumInput` discovery

vault balance based discovery

---

test/processPair.test.js

otel attrs test

---

.github/workflows/standard-test.yaml
package.json
src/modes/srouter.js
test/e2e/e2e.test.js
test/processPair.test.js

resolves #106 
PS: unit tests are part e2e tests in current CI, but it is better to separate their CI
separate unit tests CI from e2e test CI
pin pool fetch block number for tests (this should resolve flakiness of e2e tests for the most part)

separate unit tests from e2e tests

---

src/utils.js

increase rety count for viem client
resolves #124 

increase retry count for viem client

---

src/processOrders.js

resolves #128 
log more details for otel

better error for vault balance fails on otel

---

src/index.js
test/sg.test.js

better error for sg status check, resolves #127 
update building error msg

better sg status check error

---

src/utils.js
test/e2e/e2e.test.js

update to head of sushi lib
part of https://github.com/rainlanguage/arb-bot/issues/136

update sushi lib

---

src/processOrders.js
test/processPair.test.js

resolves changes required in #82 
log the block diff

track KPI opp vs exec block number diff

---

.github/workflows/build-docker.yaml
Dockerfile
arb-bot.js

resolves #149 
put the git commit and docker tag into docker file as env vars

report commit hash and docker tag in otel logs

---

arb-bot.js
src/index.js
src/processOrders.js
src/utils.js
test/arbRound.test.js
test/e2e/data.js
test/e2e/e2e.test.js
test/options.test.js
test/processPair.test.js

resolves #156 
use muliple rpcs in viem client using fallback transport

use multi rpc in viem fallback transport

---

src/dryrun.js
src/processOrders.js
src/utils.js
test/data.js
test/dryrun.test.js
test/e2e/data.js

resolves #162 
separate dryrun() that had binary search nested, into sep fns with fixing the bug + add tests for new fns

fix dryrun binary search

---

src/dryrun.js
src/processOrders.js
test/dryrun.test.js
test/processPair.test.js

resolves #160 
log current wallet balance when that err happens.

log wallet balance at err

---

package-lock.json
src/processOrders.js
test/e2e/data.js

resolves #134 
update to head of sushi lib with algebrav1 support

upate to head of sushi including algebra v1

---

README.md
cli.js
example.env
src/index.js
src/query.js

update sg query

---

src/utils.js

fix memory leak for obv3
don't use ranked for viem client

fix memory leak for obv3

---

src/config.js

fix memory leak for ob4
dont use ranked viem client

fix memory leak for obv4

---

.github/workflows/standard-test.yaml
package-lock.json
test/e2e/data.js

related to #179 
- update to head of sushi lib
- add Lines with Lynex v1/v2 to fork test

update sushi lib that includes Lynex dex support

---

package-lock.json
package.json
src/processOrders.js
src/query.js
src/utils.js
test/orders.test.js
test/utils.js

multi ob and quote setup

---

cli.js
src/account.js
test/account.test.js

bounty tokens sweeper

---

.github/workflows/standard-test.yaml
test/e2e/data.js
test/e2e/e2e.test.js

add matchain support

---

cli.js
src/config.js
src/modes/intraOrderbook.js
src/processOrders.js
src/query.js
src/sg.js
test/sg.test.js

otel meta info
related to #190 

bot meta info for otel for main branch

---

cli.js
src/index.js
src/processOrders.js

remove memoize

---

README.md
cli.js
example.env
src/config.js
src/index.js
src/modes/index.js
src/modes/interOrderbook.js
src/modes/intraOrderbook.js
src/modes/routeProcessor.js
src/processOrders.js
test/cli.test.js
test/findOpp.test.js
test/mode-interOrderbook.test.js
test/mode-intraOrderbook.test.js
test/mode-routeProcessor.test.js
test/options.test.js
test/processPair.test.js

bot wallet gas token check

---

README.md
cli.js
example.env
src/abis.js
src/account.js
src/index.js
src/processOrders.js
src/utils.js
test/account.test.js
test/cli.test.js
test/e2e/e2e.test.js

sweep to eth

---

.eslintrc.json
arb-bot.js
cli.js
src/error.js
src/processOrders.js
src/sg.js
src/utils.js
test/logger.test.js

errors severity groups

---

src/processOrders.js
src/utils.js
test/utils.test.js

resolves #207 
check bot owned orders vaults

check owned orders vaults

---

README.md
cli.js
example.env
src/account.js
src/processOrders.js
src/types.js
src/utils.js
test/account.test.js
test/utils.test.js

self fund orders

---

src/processOrders.js
test/processPair.test.js

num otel value types

---

cli.js
src/account.js
src/processOrders.js
test/account.test.js

fix funding owned vaults

---

README.md
example.env
package-lock.json
package.json
src/abis.ts
src/account.ts
src/cli.ts
src/config.ts
src/index.ts
src/modes/routeProcessor.ts
src/processOrders.ts
src/types.ts
src/utils.ts
test/cli.test.js

addresses recent issues dicussed
resolves #241 
resolves #243 
resolves #244 
- update viem to latest
- update sushi lib to latest
- remove camelot from active dexes
- add optioin for route mode, `single` | `multi`
- add rpc reporting

recent issues updates

---

src/cli.ts

rpc report

---

src/cli.ts
src/config.ts
src/index.ts
src/types.ts
test/cli.test.js

update rpc recorder

---

src/account.ts

viem nonce manager, with latest block tag

---

src/account.ts

nonce manager

---

README.md
src/config.ts
src/error.ts
src/modes/index.ts
src/modes/interOrderbook.ts
src/modes/intraOrderbook.ts
src/modes/routeProcessor.ts
src/processOrders.ts
src/types.ts
test/mode-interOrderbook.test.js
test/mode-intraOrderbook.test.js
test/mode-routeProcessor.test.js
test/processPair.test.js

report on error being  from eth node

---

src/account.ts
src/error.ts
src/processOrders.ts
src/types.ts
test/account.test.js
test/processPair.test.js

node error and nonce fix

---

README.md
example.env
src/cli.ts
src/error.ts
src/index.ts
src/processOrders.ts
src/types.ts
test/cli.test.js
test/data.js
test/e2e/e2e.test.js

gas price ultiplier option

---

package-lock.json
test/e2e/data.js

update sushi lib with gravity finance support

---

src/error.ts
src/modes/intraOrderbook.ts
src/processOrders.ts
test/findOpp.test.js
test/mode-intraOrderbook.test.js
test/processPair.test.js

improve revert error handling

---

src/modes/interOrderbook.ts
src/modes/intraOrderbook.ts
src/modes/routeProcessor.ts
src/tx.ts
src/utils.ts
test/findOpp.test.js
test/mode-intraOrderbook.test.js
test/processPair.test.js

minor update

---

src/modes/interOrderbook.ts
src/modes/routeProcessor.ts
test/e2e/data.js
test/findOpp.test.js
test/mode-interOrderbook.test.js
test/mode-routeProcessor.test.js
test/processPair.test.js

resolves #287 
add some headroom for maxInput of arb3() to account for the difference

maxInput headroom

---

src/order.ts
src/types.ts
test/orders.test.js

fix prepare orders issue

---

src/modes/index.ts
src/modes/interOrderbook.ts
src/modes/intraOrderbook.ts
src/modes/routeProcessor.ts
src/processOrders.ts
src/task.ts
src/utils.ts
test/findOpp.test.js
test/mode-interOrderbook.test.js
test/mode-intraOrderbook.test.js
test/mode-routeProcessor.test.js

fix span attr

---

src/processOrders.ts
src/signer/actions.test.ts
src/signer/actions.ts
src/signer/index.ts
src/tx.ts
test/e2e/e2e.test.js
test/findOpp.test.js
test/mode-interOrderbook.test.js
test/mode-intraOrderbook.test.js
test/mode-routeProcessor.test.js
test/processPair.test.js
test/tx.test.ts

part of #341 
This PR adds `write signer action` to list of actions, which is used to derive a signer with exact same configurations but using the `write rpcs` which usually are rpcs with men-protect features that are only used for write transactions.

write signer action

---

src/wallet/index.test.ts
src/wallet/index.ts
src/wallet/sweep.test.ts
src/wallet/sweep.ts

part of #341 
Adds `sweep` functionalities to `WalletManager` for transferring erc20 and gas tokens from worker wallet back to main wallet to `WalletManager` class (1/2)

wallet module sweep functionalities 1/2

---

src/config/yaml.ts
src/math/index.test.ts
src/math/index.ts
src/modes/interOrderbook.ts
src/modes/intraOrderbook.ts
src/modes/routeProcessor.ts
src/solver/process/log.test.ts
src/solver/process/log.ts
src/solver/process/order.ts
src/solver/process/receipt.test.ts
src/solver/process/receipt.ts
src/state/marketPrice.ts
src/task/index.test.ts
src/task/index.ts
src/utils.ts
test/utils.test.js

related to #341 
This PR removes some of the unused and deprecated functions in the utils and relocates some other to their new purposeful location

Partial utils removal

---

src/rpc/rpc.ts
src/rpc/transport.ts
src/signer/actions.test.ts
src/signer/actions.ts

test transport configs
